name: train_test_split
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pip=23.3.1
  - requests=2.24.0
  - scikit-learn=1.3.2
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
      - protobuf==3.19.1
      